---
title: Additive and Multiplicative Models in Marketing Mix
author: Aritra Biswas
date: '2018-12-29'
slug: additive-models-multiplicative-models-marketing-mix
categories: []
tags: []
---

Before starting discussion on addive and multiplicative model let us understand the marketing mix modeling problem in terms of a regression framework. After a period of execusion an organization has data associated with their execusion on various marketing tactics and sales data for the period. Let us consider NASA Ltd. is a organization who is into FMCG business. There are multiplie countries in which this organization has its presence. Brand manager of a country is interested to understand the performance of various marketing tactics in which they have execuated in the latested period. By understand the performance of the various marketing activity they want to take a data driven decision for the upcoming execusion period considering all the other factors. To understand the performace of the various tactic executated in the latested period they will comission a marketing mix modeling study. Now clearly in this context depdent varable and independent varible will vary dependeing upon the vertical in which the organization is operating. For example for FMCG the depdent variable will be amount sold in the market and for another organization who is into the television entertainment business, for them the depdent variable will be TRP. So, the dependent variable will change according to the operational domain of the organization and the indepdent variables will be anything other than the land, labour, capital and organisation. Land, labour, capital and organisation will fall under the operational cost, which is not considered under the Marketing Mix study. The capital expenditure or the marketing expendeture will be considered as the indepdent variables. Media and Promotion are the major classification of these form of marketing expenditure. 

Indepdent variables can be classified into major three sections such as base, media and promotion. There can server sub-division of the above mentioned category. For example TV, Radio, OOH, Digital everything falls under media and simularly discount, coupon, finance and other fall under the promotion category. Every other thing such as distribution, presence of some event in the modeling period, presence of holidays and other factors falls under the base category. Base simply means that if one does not invest any money in media or promotion the amount of sales it will achieve by the other means. Base is a major driver in most of the classical markets like FMCG. The base in general cases remains fixed throughout the different modeling period but the contribution of sales due to various marketing tactic changes in different modeling period. By MMM studies we try to find out the effectiveness of these tactics of the modeling period. 

Now, in different geographical location the avability of the data is not exactly the same. In many developed country where the modern trade has the maximum market share has more granual data because of the digial system. But now still in many countries which are a huge market such India, Brazil where the modern trade does not has a huge market share there the data avablity is not as rich as any depveloped country. In most of the developed countries where the is store level data avaiable the ideal form of model is Multiplicative model and in many coutries where the data is aggredgated to the market level data or the regional level aggregated data for weekly or monthly period there the ideal form of the model is additive model. Now, suppose there is market level data avaiable or some distrubtor level data avaiable for some geography then in order to apply additive linear model one has to aggregrate them into the market level data. Due to this process some detailed information are lost. But if the data is large enough it is capable of capturing the same pattern as the more detailed level data. Now, this is important to understand since this regression answers the effectiveness of each and every possible tactic it includes them all in a regression problem. Due to this one may have a huge number of variables present in the model. One must have sufficient number of samples in order to run a build a valid regression model in the dataset which is not often the case here. Avablity of the sufficient data is a problem of market mix modeling. Due to aggreating the data into the market level we losses some information and some accuracy which results into the aggregation bais for additive models. 

As we have discussed that MMM is not a time series regression therefor one key aspect should be taken underconsideration is autocorrelation. A test of autocorrelation is DW test. This sugessests that the model errors are autocorrelated or not. If the DW test statistics is around 2 then the errors are not auto correlated. As a rule of thumb one the DW test statistics should be within the range of 1.5 to 2.5 for a Market Mix Model. 




